name: Create Release

on:
  push:
    tags:
    - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build
        run: mvn -B install

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/genomic-utils.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
